### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hanegawa** [anirudh9119/rl_adversarial#1]
Hi Anirudh,
I recently read about your paper Learning Backtracking Models, ICLR'19, and I got some errors when I tried to run the code. Here is the log:
  File "fwbw_mf.py", line 153, in run_task
    for indexing in all_paths:
TypeError: 'NoneType' object is not iterable
It seems that all_paths = algo.train() at line 143 in fwbw_mf.py sometimes return NoneType for some reasons.
I guess that you added something to return a list[list[dict()]] in the rllab/algos/batch_polopt.py.
I can run soomthly with the code of https://github.com/anagabandi/nn_dynamics by Anagabandi, which may be the basic code of yours. Have you ever made similar problems? How did you solve them ? Thanks!

**Comment by anirudh9119** [comment]
Hello @hanegawa , 

Thanks for your interest.Its right we build upon the code of Anusha Nagabandi. 
Not sure what the reason is. A year or two ago someone in the lab ran the code, and was successful. 

As the code is kind of old, I can't even myself run the code (some parts are even in theano). Sorry about that. 
If I can ask, what are you looking for ? People have made advances on backtracking models, (recent literature calls it "hindsight" as compared to backtracking). May be I can be more helpful, if I know what you are looking for. 

Happy to talk offline (i.e., via email or so).

Thanks.
